### ISSUE TITLE
Blacklist follow users

### ISSUE THREAD

**Issue by fpcarva** [khrigo/instragram-follow#4]
Hello
I would like to know if there is any way to run the bot to follow people who follow a specific user, but specify a blacklist that makes the bot ignore other users.

thank you!

**Comment by khrigo** [comment]
Hello @fpcarva!

Yes, of course, the same as in the **whitelist** the code provides the parameter **blacklist**.

Examples:
`bot = Bot(whitelist="whitelist.txt")`
`bot = Bot(blacklist="blacklist.txt")`

I added this in **[/example](https://github.com/khrigo/instragram-follow/tree/master/examples)** and **[README](https://github.com/khrigo/instragram-follow/blob/master/README.md)**
